ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'CONCURSO';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'FECHA_IMPORTANTE';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'WORDSEARCH';
ALTER TYPE "GameType" ADD VALUE IF NOT EXISTS 'CROSSWORD';
ALTER TYPE "AuthProvider" ADD VALUE IF NOT EXISTS 'EMAIL';
