-- AlterEnum
ALTER TYPE "EventType" ADD VALUE 'CONCURSO';
ALTER TYPE "EventType" ADD VALUE 'FECHA_IMPORTANTE';

-- AlterEnum
ALTER TYPE "GameType" ADD VALUE 'WORDSEARCH';
ALTER TYPE "GameType" ADD VALUE 'CROSSWORD';

-- AlterEnum
ALTER TYPE "AuthProvider" ADD VALUE 'EMAIL';
